import QuestionForm from '../components/QuestionForm'

function Home({ setQuestions, setLoading, setError, setSubmitted, loading }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center px-4">
      <div className="bg-white rounded-2xl shadow-lg p-8 w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-blue-700 mb-2">
            🤖 AI Interview Prep
          </h1>
          <p className="text-gray-500 text-sm">
            Enter your details below and get custom interview questions generated by AI instantly!
          </p>
        </div>
        <QuestionForm
          setQuestions={setQuestions}
          setLoading={setLoading}
          setError={setError}
          setSubmitted={setSubmitted}
        />
        <p className="text-center text-xs text-gray-400 mt-6">
          Powered by OpenAI GPT ✨
        </p>
      </div>
    </div>
  )
}

export default Home